services:
  wildfly-app:
    image: wildfly-app
    container_name: wildfly-app  
    ports:
      - "8085:8080"
      - "9990:9990"
    volumes:
      - ./deployments:/opt/jboss/wildfly/standalone/deployments
    environment:
      - DB_HOST=127.0.0.1
      - DB_PORT=1521
      - DB_USER=master
      - DB_PASSWORD=master
      - DB_MSQL_HOST=127.0.0.1
      - DB_MSQL_PORT=1433
      - DB_MSQL_USER=sa
      - DB_MSQL_PASSWORD=123456qwe!
      - DB_MSQL_NAME=SQLSERVER_TEST
      - QUEUE_REMOTE_DESTINATION_HOST=
      - QUEUE_REMOTE_DESTINATION_PORT=8085
      - VALID_LICENSE=
      - wait_port=1521
